name: Upload to Google Play (internal)

on:
  push:
    branches: [ master ]

jobs:
  google-play:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2

    - name: Create service_account.json FROM secrets.SERVICE_ACCOUNT_JSON
      run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json

    - name: Upload bundle to Play Store (internal channel)
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJson: service_account.json
        packageName: com.starsep.sokoban.release
        releaseFile: app/build/outputs/bundle/beta/app-beta.aab
        track: internal
